sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: localhost
#    host: *****
    host: ******
    port: 3306
    database: sky_take_out
#    username: root
    username: heima
    password: '*******'
  wechat:
    # 小程序的appid
    appid: *******
    # 小程序的密钥
    secret: *******

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: *******
    access-key-secret: *********
    bucket-name: sky-heima-mcy
  redis:
#    host: localhost
#    host: **********
    host: *******
    port: 6379
    password: *******



