sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    host: localhost
    host: 101.33.220.112
    port: 3306
    database: sky_take_out
#    username: root
    username: heima
#    password: 4P+8Z8Gj#}tXsp3y
    password: '@9i2yXg6EPR^q6&j'
  wechat:
    # 小程序的appid
    appid: wxdf713fbf8afaeea5
    # 小程序的密钥
    secret: aacf999218ca41bbc472ce339eb305b5

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAIy10D7H4LvqfA
    access-key-secret: 1EO5Jl99nKKxJlY2uzZOKo9GD29VZo
    bucket-name: sky-heima-mcy
  redis:
    host: localhost
#    host: 101.33.220.112
    port: 6379
    password: eqtgghewfo



