sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 4P+8Z8Gj#}tXsp3y
  wechat:
    # 小程序的appid
    appid: wxdf713fbf8afaeea5
    # 小程序的密钥
    secret: aacf999218ca41bbc472ce339eb305b5


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAIy10D7H4LvqfA
    access-key-secret: 1EO5Jl99nKKxJlY2uzZOKo9GD29VZo
    bucket-name: sky-heima-mcy

